source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "webrick"
gem "faraday-retry"  # silences Faraday retry middleware warning
gem "fiddle"         # silence future Ruby 3.5 warning on Windows
