/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_EXO_USB_EXO_USB_PB_H_INCLUDED
#define PB_EXO_USB_EXO_USB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _exo_usb_Command {
    exo_usb_Command_GET_TELEMETRY_FAST = 1,
    exo_usb_Command_SET_CURRENT = 2,
    exo_usb_Command_SET_VELOCITY = 3,
    exo_usb_Command_SET_ABSOLUTE_ANGLE = 4,
    exo_usb_Command_SET_ANGLE = 5,
    exo_usb_Command_STOP = 6,
    exo_usb_Command_SET_JOINT_MODEL = 7,
    exo_usb_Command_SET_ANGLES = 8,
    exo_usb_Command_SET_ABSOLUTE_ANGLES = 9,
    exo_usb_Command_SET_CURRENTS = 10,
    exo_usb_Command_SET_FINGER_ANGLES = 11,
    exo_usb_Command_SET_GESTURE = 12,
    exo_usb_Command_SET_GESTURE_ANGLE = 13
} exo_usb_Command;

typedef enum _exo_usb_Status {
    exo_usb_Status_OK = 0,
    exo_usb_Status_INVALID_REQUEST = 1,
    exo_usb_Status_REJECTED = 2
} exo_usb_Status;

/* Struct definitions */
typedef struct _exo_usb_FingerAngles {
    bool has_thumb;
    int32_t thumb;
    bool has_index;
    int32_t index;
    bool has_middle;
    int32_t middle;
    bool has_ring;
    int32_t ring;
    bool has_pinky;
    int32_t pinky;
    bool has_wrist;
    int32_t wrist;
} exo_usb_FingerAngles;

typedef struct _exo_usb_Gesture {
    char name[32];
    bool has_pose;
    char pose[32];
} exo_usb_Gesture;

typedef struct _exo_usb_BatchResult {
    bool has_motors;
    uint32_t motors;
    bool has_skipped_offline;
    uint32_t skipped_offline;
    bool has_commanded;
    uint32_t commanded;
    bool has_held;
    uint32_t held;
    bool has_unknown;
    uint32_t unknown;
    bool has_zero_travel;
    uint32_t zero_travel;
} exo_usb_BatchResult;

typedef struct _exo_usb_JointModel {
    float gain;
    float time_constant;
    float max_velocity;
    float stiffness;
    float moment;
} exo_usb_JointModel;

typedef struct _exo_usb_Request {
    uint32_t sequence;
    exo_usb_Command command;
    pb_size_t motor_ids_count;
    uint32_t motor_ids[18];
    bool has_value;
    float value;
    bool has_joint_model;
    exo_usb_JointModel joint_model;
    pb_size_t values_count;
    float values[18];
    bool has_finger_angles;
    exo_usb_FingerAngles finger_angles;
    bool has_gesture;
    exo_usb_Gesture gesture;
} exo_usb_Request;

typedef PB_BYTES_ARRAY_T(607) exo_usb_Response_nx_frame_t;
typedef struct _exo_usb_Response {
    uint32_t sequence;
    exo_usb_Status status;
    bool has_nx_frame;
    exo_usb_Response_nx_frame_t nx_frame;
    bool has_batch;
    exo_usb_BatchResult batch;
} exo_usb_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _exo_usb_Command_MIN exo_usb_Command_GET_TELEMETRY_FAST
#define _exo_usb_Command_MAX exo_usb_Command_SET_GESTURE_ANGLE
#define _exo_usb_Command_ARRAYSIZE ((exo_usb_Command)(exo_usb_Command_SET_GESTURE_ANGLE+1))

#define _exo_usb_Status_MIN exo_usb_Status_OK
#define _exo_usb_Status_MAX exo_usb_Status_REJECTED
#define _exo_usb_Status_ARRAYSIZE ((exo_usb_Status)(exo_usb_Status_REJECTED+1))





#define exo_usb_Request_command_ENUMTYPE exo_usb_Command

#define exo_usb_Response_status_ENUMTYPE exo_usb_Status


/* Initializer values for message structs */
#define exo_usb_FingerAngles_init_default        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define exo_usb_Gesture_init_default             {"", false, ""}
#define exo_usb_BatchResult_init_default         {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define exo_usb_JointModel_init_default          {0, 0, 0, 0, 0}
#define exo_usb_Request_init_default             {0, _exo_usb_Command_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, exo_usb_JointModel_init_default, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, exo_usb_FingerAngles_init_default, false, exo_usb_Gesture_init_default}
#define exo_usb_Response_init_default            {0, _exo_usb_Status_MIN, false, {0, {0}}, false, exo_usb_BatchResult_init_default}
#define exo_usb_FingerAngles_init_zero           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define exo_usb_Gesture_init_zero                {"", false, ""}
#define exo_usb_BatchResult_init_zero            {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define exo_usb_JointModel_init_zero             {0, 0, 0, 0, 0}
#define exo_usb_Request_init_zero                {0, _exo_usb_Command_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, exo_usb_JointModel_init_zero, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, exo_usb_FingerAngles_init_zero, false, exo_usb_Gesture_init_zero}
#define exo_usb_Response_init_zero               {0, _exo_usb_Status_MIN, false, {0, {0}}, false, exo_usb_BatchResult_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define exo_usb_FingerAngles_thumb_tag           1
#define exo_usb_FingerAngles_index_tag           2
#define exo_usb_FingerAngles_middle_tag          3
#define exo_usb_FingerAngles_ring_tag            4
#define exo_usb_FingerAngles_pinky_tag           5
#define exo_usb_FingerAngles_wrist_tag           6
#define exo_usb_Gesture_name_tag                 1
#define exo_usb_Gesture_pose_tag                 2
#define exo_usb_BatchResult_motors_tag           1
#define exo_usb_BatchResult_skipped_offline_tag  2
#define exo_usb_BatchResult_commanded_tag        3
#define exo_usb_BatchResult_held_tag             4
#define exo_usb_BatchResult_unknown_tag          5
#define exo_usb_BatchResult_zero_travel_tag      6
#define exo_usb_JointModel_gain_tag              1
#define exo_usb_JointModel_time_constant_tag     2
#define exo_usb_JointModel_max_velocity_tag      3
#define exo_usb_JointModel_stiffness_tag         4
#define exo_usb_JointModel_moment_tag            5
#define exo_usb_Request_sequence_tag             1
#define exo_usb_Request_command_tag              2
#define exo_usb_Request_motor_ids_tag            3
#define exo_usb_Request_value_tag                4
#define exo_usb_Request_joint_model_tag          5
#define exo_usb_Request_values_tag               6
#define exo_usb_Request_finger_angles_tag        7
#define exo_usb_Request_gesture_tag              8
#define exo_usb_Response_sequence_tag            1
#define exo_usb_Response_status_tag              2
#define exo_usb_Response_nx_frame_tag            3
#define exo_usb_Response_batch_tag               4

/* Struct field encoding specification for nanopb */
#define exo_usb_FingerAngles_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SINT32,   thumb,             1) \
X(a, STATIC,   OPTIONAL, SINT32,   index,             2) \
X(a, STATIC,   OPTIONAL, SINT32,   middle,            3) \
X(a, STATIC,   OPTIONAL, SINT32,   ring,              4) \
X(a, STATIC,   OPTIONAL, SINT32,   pinky,             5) \
X(a, STATIC,   OPTIONAL, SINT32,   wrist,             6)
#define exo_usb_FingerAngles_CALLBACK NULL
#define exo_usb_FingerAngles_DEFAULT NULL

#define exo_usb_Gesture_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, STRING,   pose,              2)
#define exo_usb_Gesture_CALLBACK NULL
#define exo_usb_Gesture_DEFAULT NULL

#define exo_usb_BatchResult_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   motors,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   skipped_offline,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   commanded,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   held,              4) \
X(a, STATIC,   OPTIONAL, UINT32,   unknown,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   zero_travel,       6)
#define exo_usb_BatchResult_CALLBACK NULL
#define exo_usb_BatchResult_DEFAULT NULL

#define exo_usb_JointModel_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    gain,              1) \
X(a, STATIC,   REQUIRED, FLOAT,    time_constant,     2) \
X(a, STATIC,   REQUIRED, FLOAT,    max_velocity,      3) \
X(a, STATIC,   REQUIRED, FLOAT,    stiffness,         4) \
X(a, STATIC,   REQUIRED, FLOAT,    moment,            5)
#define exo_usb_JointModel_CALLBACK NULL
#define exo_usb_JointModel_DEFAULT NULL

#define exo_usb_Request_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   sequence,          1) \
X(a, STATIC,   REQUIRED, UENUM,    command,           2) \
X(a, STATIC,   REPEATED, UINT32,   motor_ids,         3) \
X(a, STATIC,   OPTIONAL, FLOAT,    value,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  joint_model,       5) \
X(a, STATIC,   REPEATED, FLOAT,    values,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  finger_angles,     7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gesture,           8)
#define exo_usb_Request_CALLBACK NULL
#define exo_usb_Request_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define exo_usb_Request_joint_model_MSGTYPE exo_usb_JointModel
#define exo_usb_Request_finger_angles_MSGTYPE exo_usb_FingerAngles
#define exo_usb_Request_gesture_MSGTYPE exo_usb_Gesture

#define exo_usb_Response_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   sequence,          1) \
X(a, STATIC,   REQUIRED, UENUM,    status,            2) \
X(a, STATIC,   OPTIONAL, BYTES,    nx_frame,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  batch,             4)
#define exo_usb_Response_CALLBACK NULL
#define exo_usb_Response_DEFAULT NULL
#define exo_usb_Response_batch_MSGTYPE exo_usb_BatchResult

extern const pb_msgdesc_t exo_usb_FingerAngles_msg;
extern const pb_msgdesc_t exo_usb_Gesture_msg;
extern const pb_msgdesc_t exo_usb_BatchResult_msg;
extern const pb_msgdesc_t exo_usb_JointModel_msg;
extern const pb_msgdesc_t exo_usb_Request_msg;
extern const pb_msgdesc_t exo_usb_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define exo_usb_FingerAngles_fields &exo_usb_FingerAngles_msg
#define exo_usb_Gesture_fields &exo_usb_Gesture_msg
#define exo_usb_BatchResult_fields &exo_usb_BatchResult_msg
#define exo_usb_JointModel_fields &exo_usb_JointModel_msg
#define exo_usb_Request_fields &exo_usb_Request_msg
#define exo_usb_Response_fields &exo_usb_Response_msg

/* Maximum encoded size of messages (where known) */
#define EXO_USB_EXO_USB_PB_H_MAX_SIZE            exo_usb_Response_size
#define exo_usb_BatchResult_size                 36
#define exo_usb_FingerAngles_size                36
#define exo_usb_Gesture_size                     66
#define exo_usb_JointModel_size                  25
#define exo_usb_Request_size                     344
#define exo_usb_Response_size                    656

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
