/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "exo_usb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(exo_usb_FingerAngles, exo_usb_FingerAngles, AUTO)


PB_BIND(exo_usb_Gesture, exo_usb_Gesture, AUTO)


PB_BIND(exo_usb_BatchResult, exo_usb_BatchResult, AUTO)


PB_BIND(exo_usb_JointModel, exo_usb_JointModel, AUTO)


PB_BIND(exo_usb_Request, exo_usb_Request, 2)


PB_BIND(exo_usb_Response, exo_usb_Response, 2)







