name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
            breathe \
            sphinx \
            sphinx-autodoc-typehints \
            myst-parser \
            sphinx-copybutton \
            m2r2 \
            sphinx_rtd_theme
        pip install -r requirements.txt || true

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: Create build directory
      run: mkdir -p docs/build/doxygen

    - name: Run Doxygen
      working-directory: docs
      run: |
        doxygen Doxyfile

    - name: Build docs
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        publish_branch: gh-pages